[project]
name = "load"
version = "1.0.0"
description = "Default template for PDM package"
authors = [
    {name = "rlaehgus97", email = "starkim625@gmail.com"},
]
dependencies = []
requires-python = ">=3.9" #"==3.11.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = true
